title: Map Reroll
description: |-
	This mod allows you to quickly randomize your starting map and steam vents locations. Your starting scenario, colonists, items, etc. will all stay the same.
	Now includes the map preview generator- rather than trying for random maps, you can pick exactly the map you're looking for from a nearly limitless selection.

	Of course, there is a small price to pay- in the form of unmined resources from your map.
	The resource cost is optional and can be disabled in the Options > Mod Options dialog.

	[b]Important:[/b] The HugsLib library mod must also be installed. Make sure both are enabled in the Mods menu and HugsLib is loaded first.

	The in-game description contains a brief guide. To get more info, discuss features or provide feedback, please visit the official forum thread: 
	https://ludeon.com/forums/index.php?topic=18073

	Hope you enjoy.

	Map Reroll works well with [url=https://steamcommunity.com/sharedfiles/filedetails/?id=1507370392]Kiame's Configurable Maps[/url] mod.

	[hr][/hr] 
	[h1]Warning[/h1]
	Use your best judgment when rerolling, and make sure your game has been saved.
	This mod has been designed to work with the vanilla game. Mods that include or affect map generation may not work or behave in unexpected ways.
	[hr][/hr] 
	The B19 version is still available and can be found here: [url=https://steamcommunity.com/sharedfiles/filedetails/?id=1535871514]Map Reroll (B19)[/url]

	My other mods: [url=https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]HugsLib[/url] · [url=https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]Allow Tool[/url] · [url=https://steamcommunity.com/sharedfiles/filedetails/?id=761219125]Defensive Positions[/url] · [url=https://steamcommunity.com/sharedfiles/filedetails/?id=761379469]Remote Tech[/url]
visibility: 0